msrv = "1.83"
cognitive-complexity-threshold = 30

[[disallowed-types]]
path = "std::sync::Mutex"
reason = "Use the faster and simpler non-poisonable Mutex from parking_lot instead."

[[disallowed-types]]
path = "std::sync::RwLock"
reason = "Use the faster and simpler non-poisonable RwLock from parking_lot instead."

[[disallowed-types]]
path = "std::collections::LinkedList"
reason = "LinkedList is slow and almost never the right choice."

[[disallowed-methods]]
path = "tracing_subscriber::fmt::init"
reason = "Use heartbeat::init_logging instead."
