on:
  push:
    branches:
      - main
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: setup binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - name: setup mdbook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook
      - name: setup mdbook-linkcheck
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook-linkcheck
      - name: build book
        run: mdbook build book
      - name: deploy to github pages
        uses: lmaotrigine/deploy-gh-pages-action@mistress
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: www
